name: Update Progress Log
on:
  push:
    paths:
      - 'leetcode/easy/**/*.py'
      - 'leetcode/medium/**/*.py'
      - 'leetcode/hard/**/*.py'
    branches:
      - main
jobs:
  update-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run progress log updater
        run: python scripts/update_progress_log.py
      - name: commit and push log
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add progress-log.md
          git diff --cached --quiet || git commit -m "Auto-update progress-log.md"
          git push origin main

